language: node_js
node_js:
- '0.11'
branches:
  except:
  - built
script: ".travis/script.sh"
env:
  global:
  - secure: ZBRGg1Qrdcn3P9meTlm1+lVK8ccROQ/ISdvAaVu+EFOPbsbSECq9yZ++XUDKhjHHdnjwomIT0ZJqIgFox3wjYkorwCzImH7N5kVW3K6cd/QZsSLXz1u/uNLEvgV9ghA97YwI0N7EkOUGNM1qjV0oDTwx1ff1nQA27HiW0yAjWgk=
  - secure: OfM4ybhhGUIzA6ISQ8XArE5d05XNVAtQ1END5CDSzu/PWVZLabJqprYiVL39JBLuS2B1EVyEYo8HW8iIKga8jzyfBAt+n4jp6drNKCcN3kud93fPPMgdF63pV7H6eKC7TtN0xPF0TDcYFX6fS0V/5116PdtKIKJXXUZ5UgSGulg=
